consul:
  client:
    default-zone:
      - consul:8500
    registration:
      enabled: true

micronaut:
  server:
    port: 9090
  application:
    name: product-service
  router:
    versioning:
      enabled: true
      default-version: 1
      parameter:
        enabled: false
        names: 'v,api-version'
      header:
        enabled: true
        names:
          - 'X-API-VERSION'
          - 'Accept-Version'
  security:
    authentication: bearer
    token:
      jwt:
        enabled: true
        signatures.jwks.keycloak:
          url: http://keycloak:8080/auth/realms/master/protocol/openid-connect/certs
    oauth2.clients.keycloak:
      grant-type: password
      client-id: client-product
      client-secret: 0550ddf4-517a-4704-9c0b-e9f548c83b15
      authorization:
        url: http://keycloak:8080/auth/realms/master/protocol/openid-connect/auth
datasources:
  default:
    url: jdbc:postgresql://db:5432/postgres
    driverClassName: org.postgresql.Driver
    username: admin
    password: admin
    schema-generate: CREATE_DROP
    dialect: POSTGRES
jpa:
  default:
    packages-to-scan:
      - 'com.github.fabriciolfj.providers.database.model'
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true
flyway:
  datasources:
    default:
      baseline-on-migrate: true
      enabled: true

inventory:
  host: http://inventory:9091

jpa.default.properties.hibernate.hbm2ddl.auto: update
kafka.bootstrap.servers: kafka:9092