micronaut:
  server:
    port: 8081
  application:
    name: inventoryService
  route:
    versioning:
      enabled: true
      default-version: 1
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: admin
    password: admin
    schema-generate: CREATE_DROP
    dialect: POSTGRES
jpa.default.properties.hibernate.hbm2ddl.auto: update
